services:
  - type: pserv
    name: pettour-database
    env: postgres
    plan: free 

  - type: web
    name: pettour-api
    env: java
    plan: free
    buildCommand: ./render-build.sh
    startCommand: "java -jar target/api-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: pettour-database
          property: connectionString
      - key: JWT_SECRET
        sync: false
