services:
  - type: pserv
    name: pettour-database
    plan: free
    env: docker

  - type: web
    name: pettour-api
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: pettour-database
          property: connectionString
      - key: JWT_SECRET
        sync: false
